# Обучение модели фазы после первого захвата (post-grasp).
# Датасет train: распаковать с Я.Диска (пост) в dataset_path_train ниже или передать из sbatch.
# https://disk.yandex.ru/d/OmzMhzSy0lGTMw
#
defaults:
  - train
  - _self_

task_name: open_fridge
run_name: null
launch_eval_after_train: false
use_validation: false

dataset_path_train: null
